<?php

namespace App\Models;

use App\Models\Users\UserComment;
use App\Models\Users\UserComplaint;
use Illuminate\Database\Eloquent\SoftDeletes;

class Review extends EloquentModel
{
    use SoftDeletes;

    protected $fillable = [
        'type', 'value', 'suggestion', 'label', 'response'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($review) {
            // 违规
            if ($review->suggestion == 'block') {
                $review->model->block();
            }
        });
    }

    protected $casts = [
        'response' => 'array'
    ];

    public function model()
    {
        return $this->morphTo();
    }

    public function comment()
    {
        return $this->morphedByMany(UserComment::class, 'model');
    }

    public function complaint()
    {
        return $this->morphedByMany(UserComplaint::class, 'model');
    }
}
